FROM nvidia/cuda:12.1.1-devel-ubuntu22.04
LABEL maintainer="Hugging Face"
LABEL repository="diffusers"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && \
    apt install -y software-properties-common
RUN apt update
RUN add-apt-repository ppa:deadsnakes/ppa

RUN apt update && \
    apt install -y bash \
    build-essential \
    git \
    git-lfs \
    curl \
    ca-certificates \
    libsndfile1-dev \
    libgl1 \
    python3.9 \
    python3.9-dev \
    python3-pip \
    python3.9-venv && \
    rm -rf /var/lib/apt/lists

# make sure to use venv
RUN python3.9 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# pre-install the heavy dependencies (these can later be overridden by the deps from setup.py)
RUN python3.9 -m pip install --no-cache-dir --upgrade pip && \
    python3.9 -m pip install --no-cache-dir \
    torch \
    torchvision \
    torchaudio \
    invisible_watermark && \
    python3.9 -m pip install --no-cache-dir \
    accelerate \
    datasets \
    hf-doc-builder \
    huggingface-hub \
    Jinja2 \
    librosa \
    numpy \
    scipy \
    tensorboard \
    transformers \
    omegaconf

COPY code/diffusers /diffusers
WORKDIR /diffusers
RUN pip install -e .

# Dreambooth example
WORKDIR /diffusers/examples
RUN pip install -r dreambooth/requirements.txt
RUN pip install -r dreambooth/requirements_sdxl.txt
RUN accelerate config default

CMD ["/bin/bash"]
